# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c693f6e3d8c8b74a211d2dd33202565"
name = "custom-shipping-message"
handle = "custom-shipping-message"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "checkout-valid.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
